language: java
jdk:
- oraclejdk8

env:
  global:
  - GH_REF: git@github.com:parameshjava/JavaPrograms.git

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

after_success:
- mvn clean test jacoco:report coveralls:report
- bash update-ghpages.sh

sudo: false